# Generated by Django 5.1.1 on 2024-10-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume_dispensed', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], max_length=15)),
            ],
        ),
    ]
